const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions';

// ── Summarize Notes ──────────────────────────────────────────
router.post('/summarize', auth, async (req, res) => {
  const { notes, subject, mode } = req.body;

  if (!notes || notes.trim().split(/\s+/).length < 30) {
    return res.status(400).json({ message: 'Please provide at least 30 words of notes.' });
  }

  const modeInstructions = {
    brief: 'Create a very concise summary. Bullets should be 5 most important points only. Exam points: top 5.',
    detailed: 'Create a comprehensive summary. Bullets should cover all major concepts (10-15 points). Exam points: top 10.',
    exam: 'Focus entirely on exam-relevant content. Every bullet and exam point must be something likely to appear in an exam. Exam points: top 12 most likely exam questions/answers.',
  };

  const prompt = `You are an expert academic notes summarizer${subject ? ` for the subject: ${subject}` : ''}.

Analyze these notes and create a structured summary:

NOTES:
"""
${notes.substring(0, 6000)}
"""

Mode: ${mode || 'detailed'}
Instruction: ${modeInstructions[mode] || modeInstructions.detailed}

Return ONLY a valid JSON object (no markdown, no backticks, no extra text):
{
  "summary": "A clear 3-5 sentence paragraph summarizing the main concepts covered in these notes.",
  "bullets": [
    "First key point explained clearly",
    "Second key point explained clearly"
  ],
  "keyTerms": [
    { "term": "Term Name", "definition": "Clear one-sentence definition" }
  ],
  "examPoints": [
    "Important point or likely exam question with its answer in one sentence"
  ]
}

Requirements:
- summary: 3-5 sentences, academic tone, covers main concepts
- bullets: Each bullet is a complete sentence (not just a heading)
- keyTerms: 6-10 most important technical terms with definitions
- examPoints: Points most likely to appear in exams, each self-contained
- All content must be derived strictly from the provided notes
- Return ONLY the JSON`;

  try {
    const groqResponse = await fetch(GROQ_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
        max_tokens: 3000,
      }),
    });

    if (!groqResponse.ok) {
      const errData = await groqResponse.json();
      console.error('Groq error:', errData);
      return res.status(500).json({ message: 'AI error. Please try again.' });
    }

    const groqData = await groqResponse.json();
    let raw = groqData.choices?.[0]?.message?.content?.trim();
    raw = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```$/i, '').trim();

    const result = JSON.parse(raw);
    res.json(result);
  } catch (err) {
    console.error('Summarizer error:', err);
    res.status(500).json({ message: 'AI error or invalid response. Please try again.' });
  }
});

// ── Export Summary as PDF ────────────────────────────────────
router.post('/export-pdf', auth, async (req, res) => {
  const { summary, bullets, keyTerms, examPoints, subject } = req.body;

  try {
    let html = `
      <html><head><style>
        body { font-family: 'Times New Roman', serif; font-size: 12pt; margin: 40px; color: #000; }
        h1 { font-size: 18pt; text-align: center; border-bottom: 2px solid #000; padding-bottom: 8px; }
        h2 { font-size: 14pt; margin-top: 24px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        p { line-height: 1.8; text-align: justify; }
        ul { padding-left: 20px; } li { margin-bottom: 6px; line-height: 1.6; }
        .term { font-weight: bold; } .def { color: #333; }
        .exam-point { background: #f9f9f9; padding: 6px 10px; margin-bottom: 6px; border-left: 3px solid #333; }
        .footer { text-align: center; font-size: 10pt; color: #666; margin-top: 40px; border-top: 1px solid #ccc; padding-top: 8px; }
      </style></head><body>
      <h1>📚 Notes Summary${subject ? ` — ${subject}` : ''}</h1>
      <p style="text-align:center;color:#666;font-size:10pt;">Generated by AssignmentAI • ${new Date().toLocaleDateString('en-IN')}</p>

      <h2>Summary</h2>
      <p>${summary || ''}</p>

      <h2>Key Points</h2>
      <ul>${(bullets || []).map((b) => `<li>${b}</li>`).join('')}</ul>

      <h2>Key Terms & Definitions</h2>
      ${(keyTerms || []).map((t) => `<p><span class="term">${t.term}:</span> <span class="def">${t.definition}</span></p>`).join('')}

      <h2>Exam Points</h2>
      ${(examPoints || []).map((p, i) => `<div class="exam-point">${i + 1}. ${p}</div>`).join('')}

      <div class="footer">AssignmentAI — Your Smart Study Partner</div>
      </body></html>`;

    // Return HTML as text/html for the frontend to handle
    // For a proper PDF, integrate puppeteer or pdfkit here
    // Simple approach: return the HTML and let the browser print it
    res.setHeader('Content-Type', 'text/html');
    res.send(html);
  } catch (err) {
    console.error('PDF export error:', err);
    res.status(500).json({ message: 'Export failed.' });
  }
});

module.exports = router;